### ISSUE TITLE
Wiki: Tutorials

### ISSUE THREAD

**Issue by kossy** [Kadoba/Advanced-Tiled-Loader#12]
Just wanted to point out that the tutorials on the wiki aren't complete ,It would be great if someone could finish them because it would make the Advanced Tiled Loader much more easier to learn, I would do them myself but I'm still trying to work out how to use Atl.

**Comment by Kadoba** [comment]
Yes I've needed to finish the tutorials for a while now. If I get a chance I'll start working on some next week. In the mean time if you have any questions let me know.

**Comment by kossy** [comment]
Thanks for the response and thanks for writing such an awesome library , if I have any problems I will let you know , again thanks.

**Comment by kossy** [comment]
Thanks for the awesome library and updating it :D
