### ISSUE TITLE
Map Serializer

### ISSUE THREAD

**Issue by benui-dev** [Kadoba/Advanced-Tiled-Loader#13]
The library seems super-useful.
I'm making an editor for my game, as Tiled doesn't really cover all the things I'm trying to do.
Would it be easy to make a map serializeser/saver as a counterpart to loader.lua?

**Comment by Kadoba** [comment]
I've thought about this before. I don't think it would be trivial to write but it would be useful. I'll take a crack at it.

**Comment by Kadoba** [comment]
After thinking this over and experimenting a little bit I will say this would be rather difficult to do right. Ideally, it would be great if ATL maps could be converted back into tmx files but that's going to take a lot of work. I would definitely like to do this eventually but I'm not sure when I'll get the time and motivation to do so.

**Comment by Kadoba** [comment]
With update 0.12.0 maps can now be saved. See [Saving](https://github.com/Kadoba/Advanced-Tiled-Loader/wiki/Saving) for more details.
