### ISSUE TITLE
Changing a tile doesn't seem to change its graphics.

### ISSUE THREAD

**Issue by SpiderDave** [Kadoba/Advanced-Tiled-Loader#15]
For example, if I do:

map.layers["Walls"]:set(tileX,tileY,map.tiles[5])

It will still have the graphics of whatever the old tile was.  Same issue with using tileCopy and tilePaste.

Loader version 0.11.1 (09/26/12)

**Comment by Kadoba** [comment]
Have you tried calling Map:forceRedraw() afterwards? The sprite batches won't know they have to update unless the draw range changes or you force an update.

**Comment by Kadoba** [comment]
I will be closing this issue for now. Let me know if you are still having problems.

**Comment by SpiderDave** [comment]
Ah yes, it works.  Thank you very much!
