### ISSUE TITLE
Get rid of the ".tmx" part ?

### ISSUE THREAD

**Issue by Yonaba** [Kadoba/Advanced-Tiled-Loader#16]
This is not really an issue,but more like a feature suggestion.
Why make it so that one can leave the ".tmx" part in the argument passed to  <code>ATL.Loader.load</code> ?
So that it will still be possible to write <code>ATL.Loader.load("mymap.tmx")</code>, while <code>ATL.Loader.load("mymap")</code> will still be valid, as the loader will add the ".tmx" part automatically.

**Comment by Kadoba** [comment]
Good idea. I'll put it in.

**Comment by Kadoba** [comment]
This change is included with 07bedd6bfe6d702f6a42b4fd160f66f985ab5fc6

**Comment by Yonaba** [comment]
Great, thanks!
