### ISSUE TITLE
Undefined variable in the tutorial 2 on the wiki

### ISSUE THREAD

**Issue by Yonaba** [Kadoba/Advanced-Tiled-Loader#17]
Hi,
Just to mention that <code>pad</code> argument, passed to _map:autoDrawRange()_, is undefined in the [tutorial 2](https://github.com/Kadoba/Advanced-Tiled-Loader/wiki/Tutorial-2). Look inside _love.draw()_ function.

**Comment by Kadoba** [comment]
Fixed. Thanks Yonaba.
