### ISSUE TITLE
Using SpriteBatches will make Love err on exit

### ISSUE THREAD

**Issue by Yonaba** [Kadoba/Advanced-Tiled-Loader#18]
Hi,

I noticed that, when <tt>map.useSpritebatch</tt> is set to <tt>true</tt>, everything runs fine.
But when Love reaches a part of the script where it has to terminate (_love.event.push('quit')_ or _love.event.quit()_ or just closing the window by clicking on the X button), Love crashes.
Is that a Love issue or ATL issue ?

PS: I have experienced this on Windows 7 OS (x86)

**Comment by Kadoba** [comment]
That is extremely odd. I'll look into it.

**Comment by Yonaba** [comment]
Fine.
Here are two *.love files, to illustrate the problem.
I tried with other maps, too. The problem stands still.
- [Test1-Adv-SprBatch.love](http://www.mediafire.com/?cc6dv8g1798s6gx)
- [Test1-Adv-NoSprBatch.love](http://www.mediafire.com/?uivnz9cj3o4kb67)

**Comment by Kadoba** [comment]
I'm not getting the crash on my Windows XP computer and I have no idea what could be causing this but it sounds LOVE/hardware related. <tt>useSpriteBatch</tt> should only affect <tt>TileLayer.draw()</tt> so you may want to just start deleting code from there until you find the offending line. I will test this on some other systems when I get the chance.

**Comment by Yonaba** [comment]
Well, it seems that this issue is _not_ related to ATL, but with Love's spritebatches feature.
I opened a thread on [Löve](https://love2d.org/forums/viewtopic.php?f=4&t=11255&p=67655#p67655) forums.
I am closing this issue, sorry for the inconvenience.
