### ISSUE TITLE
issue with TileLayer:draw()

### ISSUE THREAD

**Issue by eipporko** [Kadoba/Advanced-Tiled-Loader#19]
Hi, 
I am using your framework and it seems very useful, though I have some problems. I would like to draw my entities (player, enemies) between two layers using TileLayer:draw() method in this manner:
- Draw the Ground layer
- Draw entities
- Draw the rest of the layers

But it does not appear to be working

**Comment by Kadoba** [comment]
Try calling Map:_updateTileRange() before drawing. Although the intended way to accomplish what you're trying to do is use [CustomLayers](https://github.com/Kadoba/Advanced-Tiled-Loader/wiki/CustomLayer) and draw the map normally.

``` lua
-- Create a new custom layer and place it behind the ground layer
local entityLayer = map:newCustomLayer("Entities", map:layerPosition("Ground") + 1)

-- Define the layer draw function
function entityLayer:draw()
  -- Draw entities
end

-- Draw the map
function love.draw()
   map:draw()
end
```

**Comment by eipporko** [comment]
Thanks a lot, works fine in either of the two ways.

**Comment by Kadoba** [comment]
Great. I'm going to close the issue then. Let me know if you have any more trouble.
