### ISSUE TITLE
Object layer tiles are moved up visually

### ISSUE THREAD

**Issue by SpiderDave** [Kadoba/Advanced-Tiled-Loader#22]
After upgrading to the newer version of the loader, all my object layer tiles have moved up visually.  They still work as usual; it's just a visual thing, and only affects object layer tiles.

Here's an image showing the difference with game and editor:
http://i.imgur.com/iQJQ7.png

I think Object.lua line 133 might be the culprit:
di.y = di.y - th
Removing it seems to bring everything back to normal.

**Comment by Kadoba** [comment]
I can't seem to reproduce this.

**Comment by SpiderDave** [comment]
I made a stripped-down version for testing, and it's still doing it.  Here's a .love package for testing:
http://www.fileswap.com/dl/fYIWeVDDyV/

Version stuff:

Tiled Map Editor version 0.8.0
Advanced Tiled Loader 0.12.1 (10/31/12)
Windows 7 Professional
LOVE 0.8.0 (Rubber Piggy)

**Comment by Kadoba** [comment]
Thanks, you were right. It was line 133.

**Comment by Kadoba** [comment]
Fixed with 0788c1e664f656f9c2937ee3e9e3cba3e8d2b212
