### ISSUE TITLE
Lost words

### ISSUE THREAD

**Issue by floriancargoet** [Kadoba/Advanced-Tiled-Loader#3]
It looks like some words are missing in [wiki/Map](https://github.com/Kadoba/Advanced-Tiled-Loader/wiki/Map):

---

**Map.drawRange** (_default: {}_)  
The draw range of the map in pixels. Structured as {X, Y, Width, Height}. Use this to limit **HERE**

**Map.drawObjects** (_default: {}_) 
**HERE**

**Comment by Kadoba** [comment]
Yeah, the wiki is unfinished. There's likely to be a lot of missing and inaccurate things.
