### ISSUE TITLE
separate layer

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [Kadoba/Advanced-Tiled-Loader#39]
Hi,
I would like to know if is possible to works with different layer and gravity.
Example:
I have a tmx file with two layers:
- walls
- background

I would like that my player have collision and gravity with layer walls and the background is the background of the game.
Is possible to work in this way with this repository?

Thanks

**Comment by Kadoba** [comment]
ATL only loads tmx data and has the ability to render it in a simple way. Collision, physics, and all other game logic are completely separate from this so yes it is possible if you code it. That being said, ATL hasn't been in development for a while now so you might want to find an alternate library.
